# Generated by rust2rpm 28
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

%global crate tar2arx

Name:           rust-tar2arx
Version:        0.4.2
Release:        1%{?dist}
Summary:        Convert a tar archive into a arx archive

License:        MIT
URL:            https://crates.io/crates/tar2arx
Source:         %{crates_source}
Source:         tar2arx-0.4.2-vendor.tar.xz

ExclusiveArch:  %{rust_arches}

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
Convert a tar archive into a arx archive.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE-MIT
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_bindir}/tar2arx
%{_datadir}/bash-completion/completions/tar2arx
%{_datadir}/zsh/site-functions/_tar2arx
%{_datadir}/fish/vendor_completions.d/tar2arx.fish
%{_mandir}/man1/tar2arx.1*

%prep
%autosetup -n %{crate}-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install
# Generate and install shell completions
install -dm755 %{buildroot}%{_datadir}/bash-completion/completions
%{buildroot}%{_bindir}/tar2arx --generate-complete=bash > %{buildroot}%{_datadir}/bash-completion/completions/tar2arx

install -dm755 %{buildroot}%{_datadir}/zsh/site-functions
%{buildroot}%{_bindir}/tar2arx --generate-complete=zsh > %{buildroot}%{_datadir}/zsh/site-functions/_tar2arx

install -dm755 %{buildroot}%{_datadir}/fish/vendor_completions.d
%{buildroot}%{_bindir}/tar2arx --generate-complete=fish > %{buildroot}%{_datadir}/fish/vendor_completions.d/tar2arx.fish

# Generate and install man pages
install -dm755 %{buildroot}%{_mandir}/man1
%{buildroot}%{_bindir}/tar2arx --generate-man-page > %{buildroot}%{_mandir}/man1/tar2arx.1

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Sep 18 2026 Matthieu Gautier <mgautier@kymeria.fr> - 0.4.2-1
- Update version to 0.4.2
* Wed Dec 03 2025 Matthieu Gautier <mgautier@kymeria.fr> - 0.4.1-1
- Initial package
