# Generated by rust2rpm 28
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

%global crate arx

Name:           rust-arx
Version:        0.4.2
Release:        1%{?dist}
Summary:        Fast, mountable file archive based on Jubako container

License:        MIT
URL:            https://crates.io/crates/arx
Source:         %{crates_source}
Source:         arx-0.4.2-vendor.tar.xz

ExclusiveArch:  %{rust_arches}

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  fuse3-devel
BuildRequires:  fuse3
Requires:       fuse3

%global _description %{expand:
A fast, mountable file archive based on Jubako container. Replacement of
tar and zip.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE-MIT
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_bindir}/arx
%{_bindir}/auto_mount
%{_bindir}/mount_fuse_arx
%{_datadir}/bash-completion/completions/arx
%{_datadir}/zsh/site-functions/_arx
%{_datadir}/fish/vendor_completions.d/arx.fish
%{_mandir}/man1/arx.1*
%{_mandir}/man1/arx-create.1*
%{_mandir}/man1/arx-list.1*
%{_mandir}/man1/arx-dump.1*
%{_mandir}/man1/arx-extract.1*
%{_mandir}/man1/arx-mount.1*
%{_datadir}/mime/packages/arx.xml

%prep
%autosetup -n %{crate}-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install
# Generate and install shell completions
install -dm755 %{buildroot}%{_datadir}/bash-completion/completions
%{buildroot}%{_bindir}/arx --generate-complete=bash > %{buildroot}%{_datadir}/bash-completion/completions/arx

install -dm755 %{buildroot}%{_datadir}/zsh/site-functions
%{buildroot}%{_bindir}/arx --generate-complete=zsh > %{buildroot}%{_datadir}/zsh/site-functions/_arx

install -dm755 %{buildroot}%{_datadir}/fish/vendor_completions.d
%{buildroot}%{_bindir}/arx --generate-complete=fish > %{buildroot}%{_datadir}/fish/vendor_completions.d/arx.fish

# Generate and install man pages
install -dm755 %{buildroot}%{_mandir}/man1
%{buildroot}%{_bindir}/arx --generate-man-page > %{buildroot}%{_mandir}/man1/arx.1
%{buildroot}%{_bindir}/arx --generate-man-page create > %{buildroot}%{_mandir}/man1/arx-create.1
%{buildroot}%{_bindir}/arx --generate-man-page list > %{buildroot}%{_mandir}/man1/arx-list.1
%{buildroot}%{_bindir}/arx --generate-man-page dump > %{buildroot}%{_mandir}/man1/arx-dump.1
%{buildroot}%{_bindir}/arx --generate-man-page extract > %{buildroot}%{_mandir}/man1/arx-extract.1
%{buildroot}%{_bindir}/arx --generate-man-page mount > %{buildroot}%{_mandir}/man1/arx-mount.1
# Install MIME type specification
install -Dm644 misc/mime_type.xml %{buildroot}%{_datadir}/mime/packages/arx.xml

%if %{with check}
%check
%cargo_test
%endif

%post
# Update MIME database
if [ $1 -eq 1 ]; then
    /usr/bin/update-mime-database %{_datadir}/mime &> /dev/null || :
fi

%postun
# Update MIME database on removal
if [ $1 -eq 0 ]; then
    /usr/bin/update-mime-database %{_datadir}/mime &> /dev/null || :
fi

%changelog
* Thu Sep 17 2026 Matthieu Gautier <mgautier@kymeria.fr> - 0.4.2-1
- Update version to 0.4.2
* Tue Dec 02 2025 Matthieu Gautier <mgautier@kymeria.fr> - 0.4.1-1
- Initial package
